name: Instagram Archival Lambda Deploy
on:
  push:
    branches:
      - main
jobs:
  instagram-archival:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - run: |
          cd instagram-archival/lambda
          zip -r ../../instagram-archival.zip .
      - run: aws lambda update-function-code --function-name=instagram-archival --zip-file=fileb://instagram-archival.zip